version: '3'

services:
  database:
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - 5432:5432

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@database:5432/bank?sslmode=disable
    depends_on:
      - database
    entrypoint: [ "/app/wait-for.sh", "database:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]